import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar2.jsx"; // Importar Navbar
import Footer from "./components/Footer.jsx"; // Importar Footer

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar /> {/* El navbar se renderiza aquí */}
        <main>{children}</main> {/* Aquí va el contenido de cada página */}
        <Footer /> {/* El footer se renderiza aquí */}
      </body>
    </html>
  );
}